# -*- coding: utf-8 -*-
"""CSC 110_LABB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RshFIlKcN0QbC1B2TvjaAgnNLUUCP8yQ
"""

!pip install ultralytics

from google.colab import files
uploaded=files.upload()

from ultralytics import YOLO
model=YOLO("yolov8n.pt")
results=model("apple.jpg")
print("Detection Result")
for result in results:

    boxes = result.boxes

    if len(boxes) == 0:
        print("No objects were detected in the image.")
    else:
        print(f"Number of objects detected: {len(boxes)}\n")

        for i, box in enumerate(boxes):
            class_id = int(box.cls)

            object_name = result.names[class_id]
            confidence = float(box.conf)

            confidence_percent = confidence * 100

            print(f"Object {i+1}: {object_name}")
            print(f"   Confidence: {confidence_percent:.1f}%")
            print()

print("========================================")
print("Lab complete! Great job!")

from IPython.display import Image as IPImage

results[0].save(filename="output_image.jpg")

IPImage("output_image.jpg")

from google.colab import files
uploaded=files.upload()

from ultralytics import YOLO
model=YOLO("yolov8n.pt")
results=model("robot.jpg")
print("Detection Result")
for result in results:

    boxes = result.boxes

    if len(boxes) == 0:
        print("No objects were detected in the image.")
    else:
        print(f"Number of objects detected: {len(boxes)}\n")

        for i, box in enumerate(boxes):
            class_id = int(box.cls)

            object_name = result.names[class_id]
            confidence = float(box.conf)

            confidence_percent = confidence * 100

            print(f"Object {i+1}: {object_name}")
            print(f"   Confidence: {confidence_percent:.1f}%")
            print()

print("========================================")
print("Lab complete! Great job!")

from IPython.display import Image as IPImage

results[0].save(filename="output_image.jpg")

IPImage("output_image.jpg")